### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by Bhargav79**
I tried pulling request last time I committed but it didn't let me do. I had to redo the process all over again

### CODE REVIEW

**Comment by Jhorlin** [comment]
Thanks for the PR. We will use github to chat about your code. I will be critical and ask questions as I go through it. This is more about how you think, handle criticism, and defend your positions more then being correct. If I make a comment you feel is wrong don't feel shy to push back and tell me why you think I am wrong. We are building a team not a hierarchy.

**Comment by Jhorlin** [comment]
@Bhargav79 FYI got your project running. Sorry it took so long. We will reach out to you so that we can go thought it.

**Comment by Bhargav79** [comment]
@Jhorlin thanks for the update. You can see that the app didn't cover all the requirements but I was trying to build a full-fledged application which encompasses the business requirements. I can add the missing features in the next iteration if you think I was on the right path.

**Comment by Jhorlin** [comment]
@Bhargav79 you are on the right path but you are missing the important synchronization component (the service). If you want to try to complete it that is fine. For now I will close this PR. Feel free to PR again if you get time to work on it.

**Pull request closed without merging**
