### PR TITLE
Poker Planning

### PR DESCRIPTION
**Pull request by saurabh2209**
I am done with making the Poker Planning  App. Please have a look

### CODE REVIEW

**Comment by Jhorlin** [comment]
@saurabh2209 Thanks for PR. I will start reviewing it soon.

**Comment by Jhorlin** [comment]
@saurabh2209 I was able to run your project, but was looking for a server component. How do you synchronize between players?

**Comment by saurabh2209** [comment]
I am using Count.jsx component to synchronize . The Count.jsx component is rendered for each player and it will update its state saying 'player has played' once a player has either checked or fold . 
Table.jsx component maintains the state of the number of players that have played . When all players have played it will reveal the choices of all players.

**Comment by Jhorlin** [comment]
@saurabh2209 I understand.  I apologize for not being as clear as I should have. The point of poker is that two players are not a allowed to see the others cards.
In the real world how planning poker works because multiple people play without knowing each-others choice. The selection is only revealed when all choices are locked in. If we were to do this on the web, each player would have there own view allowing them to chose, but unable to see any other players cards until all players have chosen. I am going to close this PR given it does not synchronize across web pages, but you are free to try and PR again. So far it looks good and I am a fan of React.

**Comment by saurabh2209** [comment]
I will give my best to work on it and I will message you when it is done.

**Pull request closed without merging**
