### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by anigenero**
Here's the pull request for the code. Did the best with the time I had (we luckily lost internet this past weekend). If you have questions about running/building, please let me know.

### CODE REVIEW

**Comment by Jhorlin** [comment]
@anigenero,
Thanks for the PR. I will get to review as soon as possible.

**Comment by Jhorlin** [comment]
@anigenero Just started your review. I will keep you posted. I see you did not containerize your app. No worries, no one did. I am going through all the submissions and containerizing them all so that there is no cross contamination and I can catch dependencies missed in the project that can be masked by using my global dependencies.

**Comment by anigenero** [comment]
Sounds good. Yeah, I was going to be fancy and learn some Docker during this process, but that didn't work out like I hoped.

**Comment by Jhorlin** [comment]
@anigenero Closing since our review is complete. See you tomorrow.

**Pull request closed without merging**
